name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn
      - run: node data/processData
      - name: Deploy
        run: |
          git config --global user.email "deployer@dapp.lion"
          git config --global user.name "deployer"
          yarn deploy
